overrides:
  qs: '>=6.16.0'
  multer: '^2.3.0'

allowBuilds:
  '@scarf/scarf': false
  bcrypt: true
  cpu-features: false
  msgpackr-extract: false
  protobufjs: false
  ssh2: false
  unrs-resolver: false
